create the OrderItem model
TAP-SD-0624/backend-final-G3 pull request #11
Opened 2024-08-06 12:15 UTC by MahmoudMDarabaih

2024-08-06 14:14 UTC, AhmadAlBarasy requested changes
Please check the comments I provided on the code

2024-08-06 14:14 UTC, AhmadAlBarasy commented on src/models/OrderItem.ts
> +    tableName: "OrderItem",
Please pluralize the name of the table bro ;)
and also make sure the name starts with a lowercase character

2024-08-06 14:14 UTC, AhmadAlBarasy commented on src/models/OrderItem.ts
> +  {
where is the id for this table?

2024-08-06 15:48 UTC, rshgithub requested changes

2024-08-06 15:48 UTC, rshgithub commented on src/models/OrderItem.ts
> +    tableName: "OrderItem",
> Please pluralize the name of the table bro ;) and also make sure the name starts with a lowercase character

the table better to be named : tableName: 'order_items',
also he you can add :  underscored: true,   which converts the " camelCase " to " snake_case "

2024-08-06 15:48 UTC, rshgithub commented on src/models/OrderItem.ts
> +  {
add this :
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
    },

2024-08-07 11:52 UTC, MahmoudMDarabaih commented on src/models/OrderItem.ts
> +    tableName: "OrderItem",
done

2024-08-07 11:53 UTC, MahmoudMDarabaih commented on src/models/OrderItem.ts
> +  {
done

2024-08-07 11:56 UTC, AhmadAlBarasy approved these changes
محرقة يابا زعامة معلم احرق يايا

2024-08-07 11:58 UTC, rshgithub approved these changes

2024-08-07 11:58 UTC, merged