Finish Full Authentication Feature
TAP-SD-0624/backend-final-G3 pull request #18
Opened 2024-08-07 11:07 UTC by rshgithub

2024-08-08 09:57 UTC, AhmadAlBarasy requested changes
Check the comments

2024-08-08 09:57 UTC, AhmadAlBarasy commented on package.json
> +    "start": "nodemon src/server.ts",
rename the script to "dev", we'll have another one for production soon when we figure things out

2024-08-08 09:57 UTC, AhmadAlBarasy commented on package.json
> +    "build": "tsc",
"build" is an unnecessary script, we use "ts-node" to build and run source code in one step.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +      return next(new APIError("Email already in use", 401));
statusCode should be 409 "CONFLICT" or 400 "bad request", read online about both

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +      role,
End user shouldn't be able to assign himself a role of their choice, the role should be "user" by default and you can promote the user to "admin"  using an admin endpoint that should be implemented later, we can keep it like this for now and I'll refactor it soon.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +      user: newUser,
It's generally not a good practice to send back the user data after a successful sign up, due to security concerns (this response will expose the the hashed password)

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +      .json({ message: "Logged in successfully", user, token });
Also don't expose the user data here.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +
we should be sending a cookie that contains the JWT back because other than us testing the endpoint using postman, frontend developers are going to store the JWT in a cookie, so you must send them a cookie for them so they don't have to login once again, here is an **example** of sending back a cookie, adjust it so it fits our use case:
```
res.cookie('jwt', token, {
        expries: Date.now() + process.env.JWT_EXPIRES_IN * 86400000,
        httpOnly: true,
    });
```

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +    res.clearCookie("Token", { httpOnly: true, secure: isDevelopment });
remove the "secure" option for now, because we don't have an HTTPS connection during development

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +    res.clearCookie("Token", { httpOnly: true, secure: isDevelopment });
also, change "Token" to "token", and make sure that when sending a cookie when a user logs in successfully that the name of the cookie is also "token"

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/database.ts
> +const DB_PASSWORD: string | undefined = process.env.DB_PASSWORD || "123456789";
don't change the fallback values, they are just there to fix typescript types issues.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/validators/auth/authFieldsValidation.ts
we can use JOI schemas later, good for now

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/utils/jwtToken.ts
JWT configuration should be written in a .env file

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/utils/jwtToken.ts
> +const decodeToken = (token: string) => {
Error handling here is generic, fine for now, can be fixed later.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/routes/indexRoute.ts
why did you create this file?

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/models/user.ts
> +    email: {
add email validation using the validate option.

2024-08-08 09:57 UTC, AhmadAlBarasy commented on src/middlewares/authMiddleware.ts
This middleware should be able to extract the JWT from a cookie (In case the request is sent from a browser).

2024-08-09 14:54 UTC, rshgithub reviewed
all comments and notes revised

2024-08-09 14:54 UTC, rshgithub commented on src/database.ts
> +const DB_PASSWORD: string | undefined = process.env.DB_PASSWORD || "123456789";
sure , this happened by mistake

2024-08-09 14:54 UTC, rshgithub commented on src/routes/indexRoute.ts
deleted

2024-08-09 14:54 UTC, rshgithub commented on src/utils/jwtToken.ts
> +const decodeToken = (token: string) => {
converted to :
const decodeToken = (token: string) => errorHandler(
    async (req: Request, res: Response, next: NextFunction) => {
      return jwt.verify(token, process.env.JWT_SECRET as string);
    }
  );

2024-08-09 14:54 UTC, rshgithub commented on src/validators/auth/authFieldsValidation.ts
fine , just installed it and converted the validation file to JOI schema .

2024-08-09 14:54 UTC, rshgithub commented on src/utils/jwtToken.ts
done

2024-08-09 14:54 UTC, rshgithub commented on src/models/user.ts
> +    email: {
i edited it to :


`        email: {
          type: DataTypes.STRING,
          unique: true,
          allowNull: false,
          validate: {
            isEmail: {
              msg: 'Invalid email format'
            }
          }
        },`
    
  but i still think there's no need to add the validation here because it's already validating the email when users are registering their information using the register endpoint , so it will not be saved as any other text except email format .

2024-08-10 15:06 UTC, MahmoudMDarabaih approved these changes

2024-08-10 15:08 UTC, AhmadAlBarasy approved these changes

2024-08-10 15:08 UTC, MahmoudMDarabaih approved these changes

2024-08-10 15:09 UTC, AhmadAlBarasy approved these changes

2024-08-10 15:09 UTC, merged