implement swagger
TAP-SD-0624/backend-final-G3 pull request #27
Opened 2024-08-11 11:59 UTC by rshgithub

2024-08-11 13:24 UTC, AhmadAlBarasy requested changes
Please check the comments.

2024-08-11 13:24 UTC, AhmadAlBarasy commented on config/swagger.ts
move the swagger file, and the .yaml file into a folder inside the 'src' folder called `api-documentation`, it's not suitable to include any codebase files inside `config` folder, and update the imports accordingly.

2024-08-11 13:24 UTC, AhmadAlBarasy commented on swagger.yaml
don't forget to move that file into a file called `api-documentation` along with the `swagger.ts` file as mentioned in the comment on the `swagger.ts` file.

2024-08-11 13:29 UTC, AhmadAlBarasy requested changes

2024-08-11 13:29 UTC, AhmadAlBarasy commented on config/swagger.ts
> +export const setupSwagger = (app: Application) => {
add return value `void` for this function to remove eslint warning

2024-08-13 21:00 UTC, AhmadAlBarasy commented on src/controllers/categoriesController.ts
> +    res.status(202).json({
delete endpoints should return a `204 no content` response on successful deletion of the resource, and you don't have to include a body for the response because a 204 status code doesn't include a response body as it's name implies

2024-08-13 21:02 UTC, AhmadAlBarasy commented on src/services/categoryService.ts
remind me tomorrow in case I forget to discuss the topic of services so we can agree on a general way to implement them together.

2024-08-13 21:05 UTC, AhmadAlBarasy approved these changes
Nice work Rawan 🙏🏻, there are some small things to improve here and there in the Category controller and also there are some API documentation mistakes that we are going to fix tomorrow, I'll approve the PR for now 👍

2024-08-14 13:39 UTC, rshgithub commented on src/services/categoryService.ts
Yes, I was also about to discuss that with both of you.

2024-08-14 13:39 UTC, merged