Implement get all brands endpoint
TAP-SD-0624/backend-final-G3 pull request #29
Opened 2024-08-11 14:26 UTC by MahmoudMDarabaih

2024-08-11 17:24 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +      attributes: ['id', 'name'],
no need to specify the attributes when you're going to select all of the columns, just saying :>

2024-08-11 17:35 UTC, AhmadAlBarasy requested changes
Please check the comments, I promise the changes would only take 1-2 minutes from you 😂

2024-08-11 17:35 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +    res.status(201).json({
The status code should be `200 OK` not `201 Resource created`, please fix it.

2024-08-11 17:35 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +      brands,
add a fallback value in case there's no brands yet on the system, an example of this would be:
` brands: brands.length > 0 ? brands : 'No brands found.',`

2024-08-12 07:48 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +      attributes: ['id', 'name'],
I don't want to get all the data created, I only need the ID and name.

2024-08-12 07:49 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +    res.status(201).json({
done

2024-08-12 07:56 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +      brands,
done

2024-08-12 11:35 UTC, AhmadAlBarasy approved these changes
حريقة يا اسطورة

2024-08-12 11:36 UTC, merged