Implement update brand endpoint
TAP-SD-0624/backend-final-G3 pull request #36
Opened 2024-08-12 09:01 UTC by MahmoudMDarabaih

2024-08-12 12:57 UTC, AhmadAlBarasy requested changes
Please check the comments I left on each file

2024-08-12 12:57 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +    res.status(201).json(brand);
I think you fixed this statusCode but maybe the changes didn't get applied for some reason, please fix it

2024-08-12 12:57 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +    const brand = await Brand.findOne({
Instead of querying to check if the brand exists in the controller, create a service for the brands in the `services` folder and create a function `checkIfBrandExists` and call it here, exactly like how we created a userService

2024-08-12 12:57 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +    res.status(200).json({
I think it's more suitable to send a `204 no content` status code to indicate that a resource got deleted successfully and there's no need to include a JSON body because when you send a 204 status code does not include a body in the response

2024-08-12 12:57 UTC, AhmadAlBarasy commented on src/routes/brandRoutes.ts
> +brandRouter.route('/updateBrand').put(
the update route should be like the follwoing: `/api/brand/:id`, so we can chain the 3 operations `GET, PUT, DELETE` in a single endpoint.

2024-08-12 12:57 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
> +    const brand = await Brand.findOne({
check the comment I left on the deleteBrand, it has a better suggestion to use services to check brand existance.

2024-08-12 19:42 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +    res.status(201).json(brand);
done

2024-08-13 08:41 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +    const brand = await Brand.findOne({
done

2024-08-13 08:42 UTC, MahmoudMDarabaih commented on src/controllers/brandsController.ts
> +    res.status(200).json({
done

2024-08-13 08:43 UTC, MahmoudMDarabaih commented on src/routes/brandRoutes.ts
> +brandRouter.route('/updateBrand').put(
done

2024-08-13 17:45 UTC, AhmadAlBarasy approved these changes
Nice work Mahmoud 💪🏻, fingers crossed TBH for the implementation of the brand service 🔥, I did refactor the code for simplicity and fixed some bugs, check it out when you have time, I'll approve and merge the PR 👍

2024-08-13 17:45 UTC, merged