Fpbg3 54 implement product CRUD endpoints
TAP-SD-0624/backend-final-G3 pull request #40
Opened 2024-08-15 18:53 UTC by AhmadAlBarasy

2024-08-16 17:20 UTC, rshgithub requested changes
overall , you made a great effort 👍 .
Also I left some recommendations in my comments , please check them and update the code .
thanks for your time .

2024-08-16 17:20 UTC, rshgithub commented on src/controllers/productsController.ts
> +    }
when we want to craete a new product it's easier to create them depends on the category & brand names , you can use this code :

    // Validate product existence
    const productExists = await checkIfProductExists({ name });
    const category = await checkIfCategoryExists({ name: categoryName });
    const brand = await checkIfBrandExists({ name: brandName });

    if (productExists) {
      return next(new APIError('Product name already exists', 400));
    } else if (!category) {
      return next(new APIError('Category does not exist.', 400));
    } else if (!brand) {
      return next(new APIError('Brand does not exist.', 400));
    }

2024-08-16 17:20 UTC, rshgithub commented on src/controllers/productsController.ts
>        status: 'success',
as for custom product response we van make a service to customize our response structure , you can use this code :

```
const productResponseService = ({
  product,
  categoryName,
  brandName,
}: {
  product: Product;
  averageRating: number;
  categoryName: string;
  brandName: string;
}) => {
  return {
    isLimitedEdition: product.isLimitedEdition,
    id: product.id,
    name: product.name,
    brief: product.brief,
    description: product.description,
    stock: product.stock,
    price: product.price,
    discountRate: product.discountRate,
    rating: product.rating,
    brandName,
    categoryName,
  };
};
```

and make the response as :

` res.status(201).json({ status: 'success', product: responseProduct });`

2024-08-16 17:20 UTC, rshgithub commented on src/services/productService.ts
> +
you can add here: 


```
const calculateDiscountedPrice = (price: number, discountRate: number): number => {
  if (discountRate > 0) {
    const discount = (price * discountRate) / 100;
    return price - discount;
  }
  return price;
};

```

- note : you can change the approach of calculating the newPrice if you found a better way also .. 

and add the custom response service :

```
const productResponse = ({
  product,
  categoryName,
  brandName,
}: {
  product: Product;
  averageRating: number;
  categoryName: string;
  brandName: string;
}) => {
  const hasDiscount = product.discountRate > 0;
  const newPrice = hasDiscount ? calculateDiscountedPrice(product.price, product.discountRate) : undefined;

  return {
    isLimitedEdition: product.isLimitedEdition,
    id: product.id,
    name: product.name,
    brief: product.brief,
    description: product.description,
    stock: product.stock,
    price: product.price,
    ...(hasDiscount && { newPrice }),  // Only include newPrice if there's a discount
    discountRate: product.discountRate,
    rating: product.rating,
    brandName,
    categoryName,
  };
};

```

2024-08-16 17:20 UTC, rshgithub commented on src/validators/productFieldsValidation.ts
> +const updateProductValidation = Joi.object({
you can add `.optional()` also for the fields ..

2024-08-16 17:20 UTC, rshgithub commented on src/controllers/productsController.ts
> +    const { name, brief, description, price, brandId, categoryId } = req.body;
please ass the `stock`and `discountPrice `here in the req.body .

2024-08-16 17:20 UTC, rshgithub commented on src/services/productService.ts
> +
you can add this service about checking if this product is in any users order items , we may need it in some conditions later :
```

// Check if product is related to any order items
const isProductInAnyOrderItems = async(productId: string): Promise<boolean> => {
  const orderItemCount = await OrderItem.count({ where: { productId } });
  return orderItemCount > 0;
};
```

2024-08-16 18:29 UTC, AhmadAlBarasy commented on src/controllers/productsController.ts
> +    }
Done

2024-08-16 18:54 UTC, AhmadAlBarasy commented on src/controllers/productsController.ts
>        status: 'success',
Done

2024-08-16 19:09 UTC, AhmadAlBarasy commented on src/services/productService.ts
> +
Done

2024-08-16 19:13 UTC, AhmadAlBarasy commented
@rshgithub please review the changes in the latest commit and approve the merge

2024-08-17 08:57 UTC, rshgithub requested changes

2024-08-17 08:57 UTC, rshgithub commented on src/controllers/productsController.ts
> +    }
please check the category and brand name when updating by name such as you did in createProduct function because we will pass the names when updating the products data :
```

    const { name, brief, description, price, brandName, categoryName, discountRate } = req.body;
    const category = await checkIfCategoryExists({ name: categoryName });
    const brand = await checkIfBrandExists({ name: brandName });
```

and because it's repeated in two places i would recommend make one service for it and reuse it again , ( DRY Principle )  for example you can use this code :

```
const checkBrandAndCategoryExists = async(
  brandOptions: { id?: string; name?: string },
  categoryOptions: { id?: string; name?: string },
) => {
  const brand = await checkIfBrandExists(brandOptions);
  const category = await checkIfCategoryExists(categoryOptions);

  if (!brand) {
    new APIError('Brand not found', 404);
  }
  if (!category) {
    new APIError('Category not found', 404);
  }

  return { brand, category };
};
```

and use it in the controllers this way :

```
    const result = await checkBrandAndCategoryExists(
      { name: brandName },
      { name: categoryName },
    );

    if (!result) {
      return;
    }
```

2024-08-17 08:57 UTC, rshgithub commented on src/services/productService.ts
> +const productsService = async(
**recommendation :** here i would recommend adding pagination to improve performance, especially if the dataset grows larger , just as :

```
      limit = '10', // Default pagination limit
      offset = '0', // Default pagination offset
      sortBy = 'createdAt', // Default sorting field
      order = 'DESC', // Default sorting order
```

this way the service layer efficiently handle large datasets and limiting the number of products retrieved so we avoid performance issues and bottlenecks.

2024-08-17 08:57 UTC, rshgithub commented on src/services/productService.ts
> +const oneProductService = async(
**recommendation :** i would recommend to change the naming to more meaningful ones just as `checkIfProductExists`

2024-08-17 08:57 UTC, rshgithub commented on src/services/productService.ts
> +const productsService = async(
**recommendation :** i would recommend to change the naming to more meaningful ones just as `getAllProductsWithFilterService`

2024-08-17 08:57 UTC, rshgithub commented on src/services/productService.ts
> +
**note :** add filters for `new arrivals` [ which depends on the createdAt column , products that have been created for 3 months ] and `handpicked collections` [ which depends on products that have a rating above 4.5 and are less than $100 in price ] .

2024-08-17 15:16 UTC, rshgithub approved these changes

2024-08-17 15:29 UTC, merged