refactor update brand by id in the brands controllers to update image if required
TAP-SD-0624/backend-final-G3 pull request #42
Opened 2024-08-16 21:59 UTC by MahmoudMDarabaih

2024-08-17 06:04 UTC, rshgithub requested changes

2024-08-17 06:04 UTC, rshgithub commented on src/validators/brandFileldsValidation.ts
>  const updateBrandValidation = Joi.object({
please add the imagePath to the validations in create and update validations

2024-08-17 15:27 UTC, AhmadAlBarasy requested changes
Please check the comment I left on the brandsController, if something seems unclear, I can explain it to you, also, I pushed 3 commits to solve minor issues and to remove the image when deleting the brand as you told me to do.

2024-08-17 15:27 UTC, AhmadAlBarasy commented on src/controllers/brandsController.ts
A more comprehensive error handling should be added to the controller when creating a brand of updating the name of the brand to prevent the following errors from happening:
* If someone tried to create a Brand with a name that can't be a file name, for example: `"name" : "Gucci*"`, the fs module are going to throw an error that can't be handled by the express error handler (because you are using a callback-based function from the `fs` module, which will not be catched by our async handler due to the fact that it only catches errors that are caused from async functions, so we must prevent that error from happening in the first place) because an asterisk `*` is not allowed in file names and there's also other characters that are not allowed when naming files. You can use the fileNameValidator that I sent to you on slack to validate brand names before using them as a file name and you can edit the Regular expression used in it so it suits our needs.

* Same goes for updating the name of the brand, the renaming process will update the name of the image for that brand using the `fs` module which will throw an error because the file name is invalid, make sure to include file name validations for both creating and updating the brand.

2024-08-18 13:19 UTC, AhmadAlBarasy approved these changes
Nice work Mahmoud 💪, We can make the error handling more comprehensive especially for handling Multer errors but so far so good.

2024-08-20 02:58 UTC, rshgithub approved these changes

2024-08-20 03:03 UTC, rshgithub approved these changes
well done great effort .
i will also edit the swagger documentation and add all features and validations for the brand model later in another branch .

2024-08-20 06:28 UTC, merged