Fpbg3 74 crud reviews
TAP-SD-0624/backend-final-G3 pull request #51
Opened 2024-08-23 04:08 UTC by rshgithub

FPBG3-74-CRUD-ReviewsReviews API Endpoints
```

**Create a New Review**

Method: POST
Endpoint: /api/reviews
Description: Allows a user to create a new review for a product. The review includes a rating and comment. The user must be authenticated and should not have already reviewed the product.

**Get a Review by ID**

Method: GET
Endpoint: /api/reviews/:id
Description: Retrieves details of a specific review by its ID. The response includes the review details along with the product and user information.

**Update a Review by ID**

Method: PUT
Endpoint: /api/reviews/:id
Description: Updates an existing review by its ID. The review can be updated with new rating and/or comment. User must be the owner of the review or an admin.

**Delete a Review by ID**

Method: DELETE
Endpoint: /api/reviews/:id
Description: Deletes a review by its ID. User must be the owner of the review or an admin.

**Get Reviews for a Product**

Method: GET
Endpoint: /api/products/:id/reviews
Description: Retrieves all reviews for a specific product. Includes details about the reviews and the reviewer's first name.

**Get Reviews for the Current User**

Method: GET
Endpoint: /api/users/:id/reviews
Description: Retrieves all reviews made by a specific user. Only accessible to the user themselves or an admin.
```

2024-08-26 13:52 UTC, AhmadAlBarasy requested changes
please check the comments, I'll discuss these points with you in our meeting

2024-08-26 13:52 UTC, AhmadAlBarasy commented on logs/.log
please remove all log files from the commit, I added the logs folder into .gitignore file so why did they get uploaded?

2024-08-26 13:52 UTC, AhmadAlBarasy commented on src/db-files/associations.ts
what is this change? why did you add this? we already have a relation between Orders and Products and it's already working just fine

2024-08-26 13:52 UTC, AhmadAlBarasy commented on src/controllers/authController.ts
> +    const { firstName, lastName, email, balance,  mobileNumber, password } =
why adding the balance into the creation fields while it has a default value in the model? Also, The user shouldn't be able to enter his own balance at least, because this seems unrealistic at all somehow, when a user wants to signup from the frontend they're not going to enter their balance.

2024-08-27 15:47 UTC, AhmadAlBarasy commented on src/controllers/reviewsController.ts
> +    const orderItems = await OrderItem.findAll({
Could've been move into a service, but good for now 👍

2024-08-27 15:48 UTC, AhmadAlBarasy commented on src/controllers/reviewsController.ts
> +    const review = await Review.create({
Also it would be better if it was created using a service, but no problem

2024-08-27 16:07 UTC, AhmadAlBarasy commented on src/controllers/reviewsController.ts
> +    if (! await checkIfOwnerUserOrAdmin(
this service is not working correctly, if the authenticated user is admin it returns false, but no problem for now it's working as it should be (only allowing the same user that created the review to update it).

2024-08-28 20:26 UTC, rshgithub commented on src/controllers/reviewsController.ts
> +    if (! await checkIfOwnerUserOrAdmin(
admin cannot update on users reviews , it's only making sure that it's the authed user .

2024-08-28 22:04 UTC, rshgithub commented on src/db-files/associations.ts
we have discussed this at the meeting

2024-08-29 09:31 UTC, AhmadAlBarasy approved these changes

2024-08-29 09:31 UTC, merged