Fpbg3 101 implement handpicked collections
TAP-SD-0624/backend-final-G3 pull request #64
Opened 2024-08-28 00:08 UTC by rshgithub

2024-08-28 12:58 UTC, AhmadAlBarasy requested changes
Please check the 2 small fixes I requested in the comments

2024-08-28 12:58 UTC, AhmadAlBarasy commented on src/controllers/productsController.ts
> +    const filterOptions = {
Why are you creating a filter for that while we already have a virtual field called `isLimitedEdition` that is a boolean value that you can check? please fix it, and also don't forget to fix the virtual field check evaluation in the `Products` model to only be true when the stock is less than 20 items, not 10.

2024-08-28 12:58 UTC, AhmadAlBarasy commented on src/controllers/productsController.ts
> +        discountedProducts : 'No products with 15% off or more found.',
Fix the message to be `'No products found with 15% discount rate or more'`

2024-08-28 21:20 UTC, rshgithub commented on src/controllers/productsController.ts
> +        discountedProducts : 'No products with 15% off or more found.',
what the difference? both have the same meaning already .

2024-08-28 23:17 UTC, rshgithub commented on src/controllers/productsController.ts
> +    const filterOptions = {
i missed that due to quickness .
done .

2024-08-29 09:18 UTC, AhmadAlBarasy commented on src/controllers/productsController.ts
> +    const limitedEditionProducts = allProducts.filter((product) => product.isLimitedEdition);
the filtering shouldn't be done at the code level, but on the SQL level, I'll approve for now.

2024-08-29 09:19 UTC, AhmadAlBarasy approved these changes

2024-08-29 09:19 UTC, merged