implement get order data by its
TAP-SD-0624/backend-final-G3 pull request #66
Opened 2024-08-28 12:42 UTC by MahmoudMDarabaih

2024-08-28 14:18 UTC, moawiah commented on src/controllers/ordersController.ts
>          return next(new APIError('Something went wrong.', 500));
What does this sentence mean? This is a very general error catcher with no meaning.
You need to provide a better customized message for the error so you can provide better logging!

2024-08-28 14:20 UTC, moawiah commented on src/controllers/ordersController.ts
> +                attributes: ['id', 'name', 'brief'],
This code snippet looks more as a model not logic - what is its purpose? Could be added to the model? or Some other hard coded file?

2024-08-28 16:42 UTC, AhmadAlBarasy requested changes

2024-08-28 16:42 UTC, AhmadAlBarasy commented on src/controllers/ordersController.ts
> +      return next(new APIError('Order doesn\'t exist', 500));
status code should be 404, not 500

2024-08-28 16:42 UTC, AhmadAlBarasy commented on src/routes/orderRoutes.ts
> +    authMiddleware,
please add order ID validation

2024-08-28 21:30 UTC, MahmoudMDarabaih commented on src/controllers/ordersController.ts
>          return next(new APIError('Something went wrong.', 500));
done

2024-08-28 21:34 UTC, MahmoudMDarabaih commented on src/controllers/ordersController.ts
> +                attributes: ['id', 'name', 'brief'],
It's for retrieving all the order data in one instance, instead of getting multiple instances to get the required data.
I'll create a service to create get this instance for reusability.

2024-08-29 07:47 UTC, MahmoudMDarabaih commented on src/controllers/ordersController.ts
> +      return next(new APIError('Order doesn\'t exist', 500));
done

2024-08-29 08:04 UTC, MahmoudMDarabaih commented on src/routes/orderRoutes.ts
> +    authMiddleware,
done

2024-08-29 09:14 UTC, AhmadAlBarasy approved these changes

2024-08-29 09:14 UTC, merged