Scrum 21 implement the order model
TAP-SD-0624/backend-final-G3 pull request #9
Opened 2024-08-06 12:05 UTC by MahmoudMDarabaih

2024-08-06 12:33 UTC, AhmadAlBarasy requested changes
please check the comments on the code.

2024-08-06 12:33 UTC, AhmadAlBarasy commented on src/models/order.ts
> +    tableName: "order",
pluralize the name of the table

2024-08-06 12:33 UTC, AhmadAlBarasy commented on src/models/order.ts
> +          args: [
I'll approve it for now, to be checked later, please add a task for that on the backlog.

2024-08-06 15:52 UTC, rshgithub requested changes

2024-08-06 15:52 UTC, rshgithub commented on src/models/order.ts
> +    },
add this :
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
    },

2024-08-06 15:52 UTC, rshgithub commented on src/models/order.ts
> +    updatedAt: false,
add :  underscored: true,  // This will use snake_case for column names in the database instead of camelCase
suggestion : set updatedAt: ture,

2024-08-07 10:08 UTC, MahmoudMDarabaih commented on src/models/order.ts
> +    tableName: "order",
done

2024-08-07 11:42 UTC, MahmoudMDarabaih commented on src/models/order.ts
> +          args: [
done

2024-08-07 11:44 UTC, MahmoudMDarabaih commented on src/models/order.ts
> +    },
no need for that, the PK can never be null, it automatically assigned

2024-08-07 11:44 UTC, MahmoudMDarabaih commented on src/models/order.ts
> +    updatedAt: false,
we've talked about that, we will stick with the camelCase

2024-08-07 11:46 UTC, AhmadAlBarasy approved these changes
Approved!

2024-08-07 11:49 UTC, rshgithub approved these changes

2024-08-07 11:50 UTC, merged